config/routes.rb
Byfoot::Application.routes.draw do

  
  root to: "users#show"

  patch 'users/update/:id', to: 'users#update', as: :update_user

  devise_for :users

  resources :users, except: [:new ,:create, :destroy] 

  resources :places, except: [:show]

  get 'places/indexforplace/', to: 'places#userindex', as: :place_users

  get 'place/:id/:user_id', to: 'places#show', as: :show_place

  get 'places/findplace/', to: 'places#findplace', as: :find_place

  get 'places/showspot', to: 'places#showspot', as: :show_spot

  post 'places/:place_id/:id/addimage/', to:'places#addimage', as: :add_image

  get 'places/:user_id/:image_id/:place_id/showimage', to: 'places#showimage', as: :show_image

  get 'places/:image_id/:place_id/editimage', to: 'places#editimage', as: :edit_image

  patch 'places/:place_id/:place_id/updateimage/', to:'places#updateimage', as: :update_image

  delete 'places/:image_id/:place_id/deleteimage', to: 'places#destroyimage', as: :delete_image

  resources :messages, except: [:update]

  resources :friendships, except: [:show, :new, :edit]

  get '/chats', to: 'chats#index', as: :chats

  post '/chats', to: 'chats#create'

  

end

app/models/message.rb
class Message < ActiveRecord::Base
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController

	def index
		@messages = Message.where("receiver = ?", current_user.id).order('id DESC')
		@newMessages = Message.where("receiver = ? AND hasRead = ?",current_user.id, false)
		@oldMessages = Message.where("receiver = ? AND hasRead = ?",current_user.id, true)
	end

	def create
		@user = User.find(params[:user_id])
		@message = Message.new(message_params)
		@message.sender = current_user.id
		@message.receiver = @user.id
		@message.hasread = false
		if @message.save
			flash[:notice] = "Message sent"
			redirect_to user_path(@user)
		else
			render action: 'new'
		end
	end

	def new
		@user = User.find(params[:id])
		@message = Message.new
	end

	def edit
		
	end

	def show
		@user = User.find(params[:sender])
		@message = Message.find(params[:id])
		@message.hasread = true
		@message.save
	end

	def destroy
		@message = Message.find(params[:id])
		@message.destroy
		redirect_to messages_path
	end

	private 

  	def message_params
  		params.require(:message).permit(:title, :message, :sender, :receiver, :hasread)
  	end

end

app/views/messages/index.html.erb
<div id="userDiv">
<h1>Messages</h1>

<% if !@messages.empty? %>
	  	<table class="table table-striped">
		  	<th>Title</th>
		  	<th></th>
		  	<th></th>
		  	<th></th>
		  	<th></th>

		  	<% if !@newMessages.empty? %>
		  		<% @newMessages.each do |message| %>
					<tr>
						<td><%= message.title %></td>
						<td>New</td>
						<td></td>
						<td><%= link_to 'Show', message_path(message, sender: message.sender), class: 'btn btn-mini btn-primary', method: :get  %></td>
						<td><%= button_to 'Delete', message, class: 'btn btn-mini', method: :delete, confirm: 'Are your sure?'  %>
					</tr>
				<% end %>
					
		  	<% end %>

		  	<% if !@oldMessages.empty? %>
		  		<% @oldMessages.each do |message| %>
					<tr>
						<td><%= message.title %></td>
						<td></td>
						<td></td>
						<td><%= link_to 'Show', message_path(message, sender: message.sender), class: 'btn btn-mini btn-primary', method: :get  %></td>
						<td><%= button_to 'Delete', message, class: 'btn btn-mini', method: :delete, confirm: 'Are your sure?'  %></td>
					</tr>
				<% end %>
			<% end %>
		</table>
	
<% else %>
	<h4>No messages</h4>
<% end %>
</div>

app/views/messages/new.html.erb
<div id="signIn">
<h1>Send message to <%= @user.firstname %></h1>
<%= form_for @message, url: { action: :create, user_id: @user.id } do |f| %>
  <% if @message.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(@message.errors.count, "error") %> prohibited
      this place from being created:</h2>
    <ul>
    <% @message.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
  <% end %>

    <p>
      <%= f.text_field :title, placeholder: 'Title' %>
    </p>

    <p>
      <%= f.text_area :message, placeholder: 'Message' %>
    </p>
    <p>  
      <%= f.submit 'Send'%>
    </p>
<% end %>
 
<%= link_to "Back", :back %>
</div>

app/views/messages/show.html.erb
<div id="customNavbarLarge">
<div class="navbar">
  <div class="navbar-inner">
  	<ul class="nav">
		<li><%= link_to 'From:  ' + @user.firstname + ' ' + @user.lastname, user_path(@user), method: :get  %></li>
		<li><%= link_to 'Respond' ,new_message_path(id: @user.id), method: :get  %></li>
		<li><%= link_to "Back", :back %></li>
    </ul>
  </div>
</div>
</div>
<div id="userDiv">
<h1><%= @message.title %></h1>
<h4><%= @message.message %></h4>
</div>