config/routes.rb
Byfoot::Application.routes.draw do

  
  root to: "users#show"

  patch 'users/update/:id', to: 'users#update', as: :update_user

  devise_for :users

  resources :users, except: [:new ,:create, :destroy] 

  resources :places, except: [:show]

  get 'places/indexforplace/', to: 'places#userindex', as: :place_users

  get 'place/:id/:user_id', to: 'places#show', as: :show_place

  get 'places/findplace/', to: 'places#findplace', as: :find_place

  get 'places/showspot', to: 'places#showspot', as: :show_spot

  post 'places/:place_id/:id/addimage/', to:'places#addimage', as: :add_image

  get 'places/:user_id/:image_id/:place_id/showimage', to: 'places#showimage', as: :show_image

  get 'places/:image_id/:place_id/editimage', to: 'places#editimage', as: :edit_image

  patch 'places/:place_id/:place_id/updateimage/', to:'places#updateimage', as: :update_image

  delete 'places/:image_id/:place_id/deleteimage', to: 'places#destroyimage', as: :delete_image

  resources :messages, except: [:update]

  resources :friendships, except: [:show, :new, :edit]

  get '/chats', to: 'chats#index', as: :chats

  post '/chats', to: 'chats#create'

  

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable


  has_many :places, dependent: :destroy    
  has_many :friendships
  has_many :friends, :through => :friendships
  has_many :inverse_friendships, :class_name => "Friendship", :foreign_key => "friend_id"
  has_many :inverse_friends, :through => :inverse_friendships, :source => :user   
       
  has_attached_file :photo, styles: { small: "150x150>", medium: "250x250>" },
                  url: "/assets/users/:id/:style/:basename.:extension",
                  path: ":rails_root/public/assets/users/:id/:style/:basename.:extension" 
  
  validates_attachment_size :photo, less_than: 5.megabytes
  validates_attachment_content_type :photo, content_type: ['image/jpeg', 'image/png']

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!
  def index
  	@users = User.all
  end

  def show
    if params[:id] != nil
      @user = User.find(params[:id])
    else
      @user = current_user
    end
  end

  def edit
  	@user = current_user
  end

  def update
    user = User.find(params[:id])

    if user.update(user_params)
      redirect_to user
    else
      render 'edit'
    end
  end

  def user_params
  	params.require(:user).permit(:firstname, :lastname, :phone ,:information, :birthday, :country, :city, :photo)
  end

end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/edit.html.erb
<div id="signIn">
<h1>Edit information</h1>
 
<%= form_for :user, url: update_user_path(@user), html: { multipart: true}, method: :patch do |f| %>
  <% if @user.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(@user.errors.count, "error") %> prohibited
      this user from being updated:</h2>
    <ul>
    <% @user.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
  <% end %>
      
      <div class="row-fluid">
        <div class="span6">
            

            <p>
              <%= f.label :firstname %><br>
              <%= f.text_field :firstname, placeholder: 'First name' %>
            </p>
            
            <p>
              <%= f.label :country %><br>
              <%= f.text_field :country, placeholder: 'Country' %>
            </p>

            <p>
              <%= f.label :phone %><br>
              <%= f.number_field :phone, placeholder: 'Phone number' %>
            </p>

        </div>
        <div class="span6">
          <p>
              <%= f.label :lastname %><br>
              <%= f.text_field :lastname, placeholder: 'Last name' %>
            </p>
            <p>
              <%= f.label :city %><br>
              <%= f.text_field :city, placeholder: 'City' %>
            </p>
            <p>
              <%= f.label :birthday %><br>
              <%= f.date_field :birthday %>
            </p> 
        </div>
      </div>
      <p>
        <%= f.label :information %><br>
        <%= f.text_area :information, placeholder: 'Information' %>
      </p>
      <p>
        <%= f.file_field :photo %>
      </p>
  <p>
    <%= f.submit%>
  </p>
<% end %>
 
<%= link_to "Back", :back %>
</div>

app/views/users/index.html.erb
<div id="userDiv">
<h1>Users</h1>

  	<table class="table table-striped">
	  	<th>First name</th>
	  	<th>Last name</th>
	  	<th>Country</th>
	  	<th>City</th>
	  	<th></th>


  		<% @users.each do |user| %>
			<tr>
				<td><%= user.firstname %></td>
				<td><%= user.lastname %></td>
				<td><%= user.country %></td>
				<td><%= user.city %></td>
				<td><%= button_to 'Show', user_path(user), class: 'btn btn-mini btn-primary', method: :get  %></td>
			</tr>
		<% end %>
	</table>
</div>

app/views/users/indexforplace.html.erb
<h2>places for users</h2>

app/views/users/show.html.erb
<div id="userDiv">
	<div class="container-fluid">
  		<div class="row-fluid">
    		<div class="span4">
    			<%= image_tag @user.photo.url, size: "350x350"  %>
    		</div>
    		<div class="span8">	
				<table class="table table-striped">
  
  					<th>User Information</th>
  					<th></th>
					  	<tr>
					    	<th>Name</th>
					    	<td><%= @user.firstname %></td>
					  	</tr>
					  	<tr>
					    	<th>Last name</th>
					    	<td><%= @user.lastname %></td>
					  	</tr>
					  	<tr>
					    	<th>Country</th>
					   	 	<td><%= @user.country %></td>
					  	</tr>
					  	<tr>
					    	<th>City</th>
					   	 	<td><%= @user.city %></td>
					  	</tr>
					  	<% if current_user.id == @user.id || ((!current_user.friendships.find_by(friend_id: @user.id).blank? && current_user.friendships.find_by(friend_id: @user.id).accepted) || 
					  		(!@user.friendships.find_by(friend_id: current_user.id).blank? && @user.friendships.find_by(friend_id: current_user.id).accepted) 
					  		) %>
						    <tr>
						    	<th>E-mail</th>
						    	<td><%= @user.email %></td>
						  	</tr>
						    <tr>
						    	<th>Phone</th>
						    	<td><%= @user.phone %></td>
						  	</tr>
						    <tr>
						    	<th>Birthday</th>
						    	<td><%= @user.birthday %></td>
						  	</tr> 
						  	<% if !current_user.friendships.find_by(friend_id: @user.id).blank? %>
							  	<tr>
							    	<th>Friends</th>
							    	<td>Yes</td>
							  	</tr>
						  	<% end %>
					  	<% end %>
					</table>  
    		</div>
  		</div>
  	</div>	

  	<% if @user.id != current_user.id %>
  		<%= link_to 'Send message', new_message_path(id: @user.id), class: 'btn btn-mini btn-primary', method: :get  %>
  		<% if current_user.friendships.find_by(friend_id: @user.id).blank? && @user.friendships.find_by(friend_id: current_user.id).blank? %>
  				<%= link_to 'Add as friend', friendships_path(friend_id: @user.id), class: 'btn btn-mini btn-primary', method: :post  %>
  		<% elsif (!current_user.friendships.find_by(friend_id: @user.id).blank? && current_user.friendships.find_by(friend_id: @user.id).accepted) || (!@user.friendships.find_by(friend_id: current_user.id).blank? && @user.friendships.find_by(friend_id: current_user.id).accepted) %>
  			<%= link_to 'Places', places_path(id: @user.id), class: 'btn btn-mini btn-primary', method: :get  %>
  		<% end %>
  	<% end %>
	
</div>