config/routes.rb
Byfoot::Application.routes.draw do

  
  root to: "users#show"

  patch 'users/update/:id', to: 'users#update', as: :update_user

  devise_for :users

  resources :users, except: [:new ,:create, :destroy] 

  resources :places, except: [:show]

  get 'places/indexforplace/', to: 'places#userindex', as: :place_users

  get 'place/:id/:user_id', to: 'places#show', as: :show_place

  get 'places/findplace/', to: 'places#findplace', as: :find_place

  get 'places/showspot', to: 'places#showspot', as: :show_spot

  post 'places/:place_id/:id/addimage/', to:'places#addimage', as: :add_image

  get 'places/:user_id/:image_id/:place_id/showimage', to: 'places#showimage', as: :show_image

  get 'places/:image_id/:place_id/editimage', to: 'places#editimage', as: :edit_image

  patch 'places/:place_id/:place_id/updateimage/', to:'places#updateimage', as: :update_image

  delete 'places/:image_id/:place_id/deleteimage', to: 'places#destroyimage', as: :delete_image

  resources :messages, except: [:update]

  resources :friendships, except: [:show, :new, :edit]

  get '/chats', to: 'chats#index', as: :chats

  post '/chats', to: 'chats#create'

  

end

app/models/place.rb
class Place < ActiveRecord::Base

	has_many :images, dependent: :destroy
	belongs_to :user

	geocoded_by :address
	after_validation :geocode

end

app/controllers/places_controller.rb
class PlacesController < ApplicationController
  def index
    if params[:id] != nil
      @user = User.find(params[:id])
    else
      @user = current_user
    end
      @places = @user.places
      @hash = Gmaps4rails.build_markers(@places) do |place, marker|
      marker.lat place.latitude
      marker.lng place.longitude
	end

  end

  def new
  	@user = current_user
  	@place = @user.places.new
  end

  def findplace
    @user = current_user
    @client = GooglePlaces::Client.new('AIzaSyBc1aKSdIj4Y4pszwFHO8cPxXY3llVf6Us')
    if params[:search] != nil
      location = Geocoder.coordinates(params[:search])
      if location != nil && (!location.first.blank? && !location.second.blank?)
        types = []
        if params[:food] == 'true'
          types << 'food'
        end
        if params[:airport] == 'true'
          types << 'airport'
        end
        if params[:atm] == 'true'
          types << 'atm'
        end
        if params[:cafe] == 'true'
          types << 'cafe'
        end
        if params[:gym] == 'true'
          types << 'gym'
        end
        if params[:night_club] == 'true'
          types << 'night_club'
        end
        if params[:taxi_stand] == 'true'
          types << 'taxi_stand'
        end
        if params[:shopping_mall] == 'true'
          types << 'shopping_mall'
        end

        if types.size == 0
          types = 'food'
        elsif types.size == 1
          types = types.first
        end

        @spots = @client.spots(location.first, location.second, :types => types)
        if @spots.blank? || @spots.size == 0
          @places = []
          flash[:notice] = "No place found, try again"
          render action: 'findplace'
        else
          @places = []
          @spots.each do |spot|
            place = Place.new
            place.name = spot.name
            place.latitude = spot.lat
            place.longitude = spot.lng
            place.address = spot.vicinity
            @places << place
          end
        end
      else
        @places = []
        flash[:notice] = "No place found, try again"
        render action: 'findplace'
      end
    else
      @places = []
    end
  end

  def create
  	@user = current_user
  	@place = @user.places.build(place_params)
  	if @place.save
  	  	if @place.longitude.blank? || @place.latitude.blank?
  	  		@place.destroy
  	  		flash[:notice] = "Place not found, try again"
  	  		render action: 'new'
  	  	else
  	  		redirect_to places_path
  	  	end
  	else
  	  	render action: 'new'
  	end
  	
  end

  def userindex
    @places = Place.where( "latitude = ? AND longitude = ?", params[:latitude], params[:longitude] )
    @place = @places.first
    @users = []
    @places.each do |place|
      if place.user_id != current_user.id
        @users << User.find(place.user_id)
      end
    end

    @hash = Gmaps4rails.build_markers(@place) do |place, marker|
      marker.lat place.latitude
      marker.lng place.longitude
    end

  end

  def showspot
    places = []
    @place = Place.new
    @place.name = params[:name]
    @place.address = params[:address]
    @place.latitude = params[:lat]
    @place.longitude = params[:lng]
    places << @place
    @hash = Gmaps4rails.build_markers(places) do |place, marker|
      marker.lat place.latitude
      marker.lng place.longitude
    end
  end

  def edit
  	@place = Place.find(params[:id])
  end

  def show
    @user = User.find(params[:user_id])
  	@place = Place.find(params[:id])
  	@images = @place.images
  	@image = Image.new	
  end

  def update
  	@place = Place.find(params[:id])
    if @place.update(place_params)
        if @place.longitude.blank? || @place.latitude.blank?
          @place.destroy
          flash[:notice] = "Place not found, try again"
          render action: 'edit'
        else
          redirect_to places_path
        end
    else
        render action: 'edit'
    end

  end

  def destroy
  	@place = Place.find(params[:id])
  	@place.destroy
  	redirect_to places_path
  end

  def addimage
  	@place = Place.find(params[:place_id])
  	@image = @place.images.build(image_params)
  	@image.save
  	redirect_to show_place_path(id: @place.id, user_id: current_user.id)
  end

  def showimage
    @user = User.find(params[:user_id])
  	@place = Place.find(params[:place_id])
  	@image = Image.find(params[:image_id])
  end

  def editimage
  	@place = Place.find(params[:place_id])
  	@image = Image.find(params[:image_id])
  end

  def updateimage
  	@place = Place.find(params[:place_id])
  	image = Image.find(params[:image_id])

    if image.update(image_params)
      redirect_to show_place_path(id: @place.id, user_id: current_user.id)
    else
      render 'editimage'
    end
  end

  def destroyimage
  	@place = Place.find(params[:place_id])
  	@image = Image.find(params[:image_id])
  	@image.destroy
  	redirect_to show_place_path(id: @place.id, user_id: current_user.id)
  end

  private 

  def place_params
  	params.require(:place).permit(:name, :address, :longitude, :latitude, :user_id)
  end

  def image_params
  	params.require(:image).permit(:title, :description, :place_id, :image)
  end
end

app/helpers/places_helper.rb
module PlacesHelper
end

app/views/places/edit.html.erb
<div id="signIn">
<h1>edit place</h1>
<%= form_for @place, url: { action: :update } do |f| %>
  <% if @place.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(@place.errors.count, "error") %> prohibited
      this place from being created:</h2>
    <ul>
    <% @place.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
  <% end %>

    <p>
      <%= f.text_field :name, placeholder: 'Name of place' %>
    </p>

    <p>
      <%= f.text_field :address, placeholder: 'Address (Country, City, Address or Name)' %>
    </p>
    <p>  
      <%= f.submit%>
    </p>
<% end %>
 
<%= link_to "Back", :back %>
</div>

app/views/places/editimage.html.erb
<div id="signIn">
<h1>Edit image</h1>

<%= form_for @image, url: update_image_path(image_id: @image.id, place_id: @place.id), :html => { :multipart => true } do |f| %>   
    <p>
      <%= f.text_field :title, placeholder: 'Title' %>
    </p>

    <p>
      <%= f.text_area :description, placeholder: 'Description' %>
    </p>

      <%= f.file_field :image %>
      <p>  
          <%= f.submit 'Add image'%>
      </p>
  <% end %>
<%= link_to "Back", :back %>
</div>

app/views/places/findplace.html.erb
<div id="userDiv">
<h1>Find place</h1>

<%= form_tag find_place_path(current_user), :method => 'get' do %>
  <p>
    <%= text_field_tag :search, params[:search], placeholder: 'Place (e.g Stockholm, Sweden)' %>
    </p>
    <%= check_box_tag :food, checked = true%> Food
    <%= check_box_tag :airport, checked = true %> Airport
	  <%= check_box_tag :atm, checked = true %> ATM
    <%= check_box_tag :cafe, checked = true %> Cafe<br />
    <%= check_box_tag :gym, checked = true %> Gym
    <%= check_box_tag :night_club, checked = true %> Club
    <%= check_box_tag :taxi_stand, checked = true %> Taxi
    <%= check_box_tag :shopping_mall, checked = true %> Shopping
	</br>
	</br>
<p>
    <%= submit_tag "Search Place", :name => nil, class: 'btn btn-primary' %>
  </p>
<% end %>

<% if @places.size > 0 %>
  	<table class="table table-striped">
	  	<th>Name</th>
      <th>Address</th>

  		<% @places.each do |place| %>
			<tr>
				<td><%= place.name %></td>
        <td><%= place.address %></td>
        <td><%= link_to 'Show', show_spot_path(name: place.name, lat: place.latitude, lng: place.longitude, address: place.address), class: 'btn btn-mini btn-primary', method: :get  %></td>
			</tr>
		<% end %>
	</table>
<% end %>
</div>

app/views/places/index.html.erb
<script src="//maps.google.com/maps/api/js?v=3.13&amp;sensor=false&amp;libraries=geometry" type="text/javascript"></script>
<script src='//google-maps-utility-library-v3.googlecode.com/svn/tags/markerclustererplus/2.0.14/src/markerclusterer_packed.js' type='text/javascript'></script>
<div id="userDiv">
<% if @user.id == current_user.id %>
	<h1>Your Places</h1>
<% else %>
	<h1><%= @user.firstname %> <%= @user.lastname %>´s places</h1>
<% end %>

  <div id="map"></div>
<div id="placesTable">
  	<table class="table table-striped">
	  	<th>Name</th>
	  	<th>Address</th>
	  	<th>Longitude</th>
	  	<th>Latitude</th>
	  	<th></th>
	  	<% if @user.id == current_user.id %>
		  	<th>Actions</th>
		  	<th></th>
	  	<% end %>


  		<% @places.each do |place| %>
			<tr>
				<td><%= place.name %></td>
				<td><%= place.address %></td>
				<td><%= place.longitude %></td>
				<td><%= place.latitude %></td>
				<td><%= button_to 'Show', show_place_path(id: place.id, user_id: @user.id), class: 'btn btn-mini btn-primary', method: :get  %></td>
				<% if @user.id == current_user.id %>
					<td><%= button_to 'Edit', edit_place_path(place), class: 'btn btn-mini btn-primary', method: :get  %></td>
					<td><%= button_to 'Delete', place, class: 'btn btn-mini', method: :delete, confirm: 'Are your sure?'  %></td>
				<% end %>
			</tr>
		<% end %>
	</table>
</div>
</div>

<script type="text/javascript">
handler = Gmaps.build('Google');
handler.buildMap({ provider: {}, internal: {id: 'map'}}, function(){
markers = handler.addMarkers(<%=raw @hash.to_json %>);
  handler.getMap().setZoom(1000)
  handler.bounds.extendWith(markers);
  handler.fitMapToBounds();

});
</script>

app/views/places/new.html.erb
<div id="signIn">
<h1>Add new place</h1>
<%= form_for @place, url: { action: :create } do |f| %>
  <% if @place.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(@place.errors.count, "error") %> prohibited
      this place from being created:</h2>
    <ul>
    <% @place.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
  <% end %>

    <p>
      <%= f.text_field :name, placeholder: 'Name of place' %>
    </p>

    <p>
      <%= f.text_field :address, placeholder: 'Address (Country, City, Address or Name)' %>
    </p>
    <p>  
      <%= f.submit%>
    </p>
<% end %>
 
<%= link_to "Back", :back %>
</div>

app/views/places/show.html.erb
<div id="customNavbar">
<div class="navbar">
  <div class="navbar-inner">
  	<ul class="nav">
    <% if @user.id == current_user.id %>
		<li><%= link_to 'Add image', '#signIn' %></li>
		<li><%= link_to 'Other visitors', place_users_path(latitude: @place.latitude, longitude: @place.longitude), method: :get %></li>
	<% else %>
		<li><%= link_to @user.firstname + ' ' + @user.lastname, user_path(@user), method: :get  %></li>
	<% end %>
    </ul>
  </div>
</div>
</div>
<div id="userDiv">
	
	<h1><%= @place.name %> </h1>
	<h2><%= @place.address %></h2>
	<%  if @images.size > 0%>
		<% @images.each do |image| %>
			<%= link_to show_image_path(user_id: @user.id, image_id: image.id, place_id: @place.id) do %>
			    <%= image_tag image.image.url(:medium) %>
			<% end %>
		<% end %>
	<% else %>
		<h2>No images</h2>
	<% end %>
	
</div>

<% if @user.id == current_user.id %>
	<div id="signIn">
	<h1>Add new image</h1>

	<%= form_for @image, url: add_image_path(place_id: @place.id), :html => { :multipart => true } do |f| %>   
	    <p>
	      <%= f.text_field :title, placeholder: 'Title' %>
	    </p>

	    <p>
	      <%= f.text_area :description, placeholder: 'Description' %>
	    </p>

	      <%= f.file_field :image %>
	      <p>  
	          <%= f.submit 'Add image'%>
	      </p>
	  <% end %>
	<%= link_to "Back", :back %>
	</div>
<% end %>

app/views/places/showimage.html.erb
<div id="customNavbar">
<div class="navbar">
  <div class="navbar-inner">
  	<ul class="nav">
    <% if @user.id == current_user.id %>
		<li><%= link_to 'Edit', edit_image_path(image_id: @image.id, place_id: @place.id ), method: :get  %> </li>
		<li><%= link_to 'Delete', delete_image_path(image_id: @image.id), method: :delete, confirm: 'Are your sure?'  %></li>
	<% else %>
		<li><%= link_to @user.firstname + ' ' + @user.lastname, user_path(@user), method: :get  %></li>
	<% end %>
	<li><%= link_to "Back", :back %></li>
    </ul>
  </div>
</div>
</div>

<div id="userDiv">
	<h1><%= @image.title %></h1>
	<%= image_tag @image.image.url %>
	<p>
		<%= @image.description %>
	</p>
</div>

app/views/places/showspot.html.erb
<script src="//maps.google.com/maps/api/js?v=3.13&amp;sensor=false&amp;libraries=geometry" type="text/javascript"></script>
<script src='//google-maps-utility-library-v3.googlecode.com/svn/tags/markerclustererplus/2.0.14/src/markerclusterer_packed.js' type='text/javascript'></script>
<div id="userDiv">
	<h1>Add new place</h1>
<div id="signIn">
<%= form_for @place, url: { action: :create } do |f| %>
  <% if @place.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(@place.errors.count, "error") %> prohibited
      this place from being created:</h2>
    <ul>
    <% @place.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
  <% end %>

    <p>
      <%= f.text_field :name, placeholder: 'Name of place' %>
    </p>
    <p>
      <%= f.text_field :address, placeholder: 'Address (Country, City, Address or Name)' %>
    </p>
    <p>  
      <%= f.submit 'Add Place'%>
    </p>
<% end %>
</div>
<div id="map"></div>
</div>

<script type="text/javascript">
handler = Gmaps.build('Google');
handler.buildMap({ provider: {}, internal: {id: 'map'}}, function(){
markers = handler.addMarkers(<%=raw @hash.to_json %>);
  handler.getMap().setZoom(1000)
  handler.bounds.extendWith(markers);
  handler.fitMapToBounds();

});
</script>

app/views/places/userindex.html.erb
<script src="//maps.google.com/maps/api/js?v=3.13&amp;sensor=false&amp;libraries=geometry" type="text/javascript"></script>
<script src='//google-maps-utility-library-v3.googlecode.com/svn/tags/markerclustererplus/2.0.14/src/markerclusterer_packed.js' type='text/javascript'></script>
<div id="userDiv">
	<h1>Other visitors of place</h1>
  <div id="map"></div>
 <% if !@users.empty? %>
<div id="placesTable">
  	<table class="table table-striped">
	  	<th>First name</th>
	  	<th>Last name</th>
	  	<th>Country</th>
	  	<th>City</th>
	  	<th></th>
	  	<th></th>

  		<% @users.each do |user| %>
  		<% place = @places.where(user_id: user.id).first %>
			<tr>
				<td><%= user.firstname %></td>
				<td><%= user.lastname %></td>
				<td><%= user.country %></td>
				<td><%= user.city %></td>
				<td><%= link_to user.firstname, user_path(user), class: 'btn btn-mini btn-primary', method: :get  %></td>
				<td><%= link_to 'Place', show_place_path(id: place.id, user_id: user.id), class: 'btn btn-mini btn-primary', method: :get  %></td>
			</tr>
		<% end %>
	</table>
</div>
<% else %>
	<h4>No other visitors</h4>
<% end %>
</div>

<script type="text/javascript">
handler = Gmaps.build('Google');
handler.buildMap({ provider: {}, internal: {id: 'map'}}, function(){
markers = handler.addMarkers(<%=raw @hash.to_json %>);
  handler.getMap().setZoom(1000)
  handler.bounds.extendWith(markers);
  handler.fitMapToBounds();

});
</script>