config/routes.rb
Byfoot::Application.routes.draw do

  
  root to: "users#show"

  patch 'users/update/:id', to: 'users#update', as: :update_user

  devise_for :users

  resources :users, except: [:new ,:create, :destroy] 

  resources :places, except: [:show]

  get 'places/indexforplace/', to: 'places#userindex', as: :place_users

  get 'place/:id/:user_id', to: 'places#show', as: :show_place

  get 'places/findplace/', to: 'places#findplace', as: :find_place

  get 'places/showspot', to: 'places#showspot', as: :show_spot

  post 'places/:place_id/:id/addimage/', to:'places#addimage', as: :add_image

  get 'places/:user_id/:image_id/:place_id/showimage', to: 'places#showimage', as: :show_image

  get 'places/:image_id/:place_id/editimage', to: 'places#editimage', as: :edit_image

  patch 'places/:place_id/:place_id/updateimage/', to:'places#updateimage', as: :update_image

  delete 'places/:image_id/:place_id/deleteimage', to: 'places#destroyimage', as: :delete_image

  resources :messages, except: [:update]

  resources :friendships, except: [:show, :new, :edit]

  get '/chats', to: 'chats#index', as: :chats

  post '/chats', to: 'chats#create'

  

end

app/views/layouts/_body.html.erb
<%= yield %>
<%= yield :scripts %>

app/views/layouts/_header.html.erb
<% if user_signed_in? %>
<nav class="navbar navbar-default navbar-fixed-top" role="navigation">
	<div class="container-fluid">
		<div id="navbar">
			<div id="navbarIcon">
			<%= image_tag 'Icon-Small.png', alt: 'icon' %>
			</div>
	        <ul class="nav navbar-nav">
	            <li><%= link_to 'Users', users_path, method: :get %></li>
	            <li><%= link_to 'Find Place', find_place_path(current_user), method: :get %></li>
	            <li><%= link_to 'Add Place', new_place_path, method: :get %></li>
	            <li><%= link_to 'My Places', places_path(id: current_user.id), method: :get %></li>
	            <li><%= link_to 'My Friends', friendships_path, method: :get %></li>
	            <li><%= link_to 'Home', user_path(current_user), method: :get %></li>
	            <li><%= link_to 'Chat', chats_path, method: :get %></li>
	        </ul>
	        <div id="dropdown">
        		<ul class="nav navbar-nav navbar-right">
        			<ul class="nav navbar-nav">
	            		<li><%= link_to 'My Messages', messages_path, method: :get %></li>
	            	</ul>
        			<li class="dropdown">
          				<a href="#" class="dropdown-toggle" data-toggle="dropdown"><%= current_user.email %> <b class="caret"></b></a>
          				<ul class="dropdown-menu">
            				<li><%= link_to 'Edit user info', edit_user_path(current_user.id), method: 'get'%></li>
            				<li><%= link_to 'Edit login info', edit_user_registration_path(current_user.id), method: 'get'%></li>
            				<li><%= link_to 'Log out', destroy_user_session_path, method: "delete"%></li>
          				</ul>
        			</li>
      			</ul>
  			</div>
		</div>
	</div>
</nav>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Byfoot</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>
	<%= render 'layouts/header' %>
	<p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>

	<%= render 'layouts/body' %>
	<%= render 'layouts/footer' %>



</body>
</html>